name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Get installed Playwright version
        run: |
          NPM_JSON="$(npm info @playwright/test dist --json)"
          PLAYWRIGHT_SHA=$(node -e "console.log(JSON.parse(\"$NPM_JSON\").data.shasum)")
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_SHA" >> $GITHUB_ENV
          echo "Playwright VERSION SHA: $PLAYWRIGHT_SHA"
      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with: 
          path: |
            /home/runner/.cache/ms-playwright
          key: "${{ runner.os }}-playwright-v3-${{env.PLAYWRIGHT_VERSION}}"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps  
      - name: Uninstall conflicting packages
        run: |
          sudo apt-get autoremove
          sudo apt-get autoclean
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
          docker --version
          docker-compose --version
      - name: Start Docker Compose services
        run: docker-compose up -d
      - name: Wait for app to start
        run: while ! nc -z localhost 8087; do sleep 1; done
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Stop Docker Compose services
        run: docker-compose down
